name: serial_section_overlay
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=4.2.0
  - aom=3.6.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asciitree=0.3.3
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - blessed=1.19.1
  - blosc=1.21.3
  - brotli=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=3.0.0
  - comm=0.2.1
  - contourpy=1.2.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask-core=2024.4.1
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fasteners=0.17.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - giflib=5.2.2
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.34.0
  - importlib-metadata=7.0.1
  - importlib-resources=6.4.0
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.1.3
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.27
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp-base=1.4.0
  - libzopfli=1.0.3
  - llvm-openmp=18.1.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - msgpack-python=1.0.7
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numcodecs=0.12.1
  - numpy=1.26.4
  - openjdk=8.0.382
  - openjpeg=2.4.0
  - openssl=3.2.1
  - overrides=7.4.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyjnius=1.6.1
  - pyparsing=3.1.2
  - python=3.9.19
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-image=0.19.3
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - send2trash=1.8.2
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - threadpoolctl=3.4.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zarr=2.17.2
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aicspylibczi==3.1.2
      - bounded-pool-executor==0.0.3
      - colorama==0.4.6
      - colour-science==0.4.4
      - dnspython==2.6.1
      - elementpath==4.4.0
      - email-validator==2.1.1
      - fastcluster==1.2.6
      - filelock==3.13.4
      - jgo==1.0.5
      - jpype1==1.5.0
      - lxml==5.2.1
      - mpmath==1.3.0
      - ome-types==0.3.4
      - opencv-contrib-python-headless==4.9.0.80
      - opencv-python==4.9.0.80
      - pandas==1.5.3
      - pillow==9.5.0
      - pint==0.23
      - pqdm==0.2.0
      - pydantic==1.10.15
      - pyvips==2.2.2
      - pywavelets==1.6.0
      - scyjava==1.9.1
      - setuptools==69.5.1
      - shapely==2.0.3
      - simpleitk==2.3.1
      - sympy==1.12
      - tifffile==2024.2.12
      - torch==2.2.2
      - tqdm==4.66.2
      - tzdata==2024.1
      - valis-wsi==1.0.4
      - weightedstats==0.4.1
      - xmlschema==3.2.1
prefix: /Users/ferris/opt/anaconda3/envs/serial_section_overlay
